# Generated by Django 2.1.7 on 2019-08-18 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_listing_app.ModelBase')),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=255)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('genre', models.CharField(max_length=250)),
                ('editors_choice', models.BooleanField(default=False)),
            ],
            bases=('game_listing_app.modelbase',),
        ),
    ]
