# Generated by Django 2.1.7 on 2019-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_listing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(max_length=255),
        ),
    ]
